apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-secret-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
       app: nginx
    spec:

     volumes:
      - name: secret-sample-volume
        secret:
         secretName: my-sample-secret

     containers:
     - name: nginx
       image: nginx:alpine

       env:
        - name: key1
          valueFrom: 
           secretKeyRef:
            name: my-sample-secret
            key: Employee_Name 

        - name: key2
          valueFrom:
           secretKeyRef:
            name: my-sample-secret
            key: index.html             

       volumeMounts:
        - name: secret-sample-volume
          mountPath: /usr/share/nginx/html

       ports:      
        - containerPort: 80