apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-no-execute-demo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "degredation"
        operator: "Equal"
        value: "commence"
        effect: "NoExecute"
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80