apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-demo
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        operating-system: windows
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80