apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          ports:
          - containerPort: 27017

          volumeMounts:
          - name: mongo-db-volume
            mountPath: /data/db

      volumes:
      - name: mongo-db-volume
        persistentVolumeClaim:
          claimName: mongo-pvc-demo
