apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-preferred-demo
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: operating-system
                operator: In
                values:
                - windows
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80