apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: my-sample-volume
              mountPath: /sample-folder/madhu 
      volumes:
         - name: my-sample-volume
           emptyDir: {}