apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 250Mi # how much storage you want to allocate
  accessModes:
    - ReadWriteMany # What kind of access mode you want
  local:
    path: /data/db # path on the host machine
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
