apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      name: app
      labels:
        tier: app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80


# Probes
#   - types of probes : Live, readiness, startup
# Volumes, VolumeMount
